/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BlocXMLUiModule extends AbstractBlocXMLUiModule {

	public BlocXMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
