/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.blocXML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.blocXML.Link#getCompID <em>Comp ID</em>}</li>
 *   <li>{@link org.xtext.example.blocXML.Link#getPortID <em>Port ID</em>}</li>
 *   <li>{@link org.xtext.example.blocXML.Link#getPortName <em>Port Name</em>}</li>
 *   <li>{@link org.xtext.example.blocXML.Link#getPortName2 <em>Port Name2</em>}</li>
 *   <li>{@link org.xtext.example.blocXML.Link#getBaliseFermante <em>Balise Fermante</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.blocXML.BlocXMLPackage#getLink()
 * @model
 * @generated
 */
public interface Link extends EObject
{
  /**
   * Returns the value of the '<em><b>Comp ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp ID</em>' attribute.
   * @see #setCompID(String)
   * @see org.xtext.example.blocXML.BlocXMLPackage#getLink_CompID()
   * @model
   * @generated
   */
  String getCompID();

  /**
   * Sets the value of the '{@link org.xtext.example.blocXML.Link#getCompID <em>Comp ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp ID</em>' attribute.
   * @see #getCompID()
   * @generated
   */
  void setCompID(String value);

  /**
   * Returns the value of the '<em><b>Port ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port ID</em>' attribute.
   * @see #setPortID(String)
   * @see org.xtext.example.blocXML.BlocXMLPackage#getLink_PortID()
   * @model
   * @generated
   */
  String getPortID();

  /**
   * Sets the value of the '{@link org.xtext.example.blocXML.Link#getPortID <em>Port ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port ID</em>' attribute.
   * @see #getPortID()
   * @generated
   */
  void setPortID(String value);

  /**
   * Returns the value of the '<em><b>Port Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port Name</em>' attribute.
   * @see #setPortName(String)
   * @see org.xtext.example.blocXML.BlocXMLPackage#getLink_PortName()
   * @model
   * @generated
   */
  String getPortName();

  /**
   * Sets the value of the '{@link org.xtext.example.blocXML.Link#getPortName <em>Port Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port Name</em>' attribute.
   * @see #getPortName()
   * @generated
   */
  void setPortName(String value);

  /**
   * Returns the value of the '<em><b>Port Name2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port Name2</em>' attribute.
   * @see #setPortName2(String)
   * @see org.xtext.example.blocXML.BlocXMLPackage#getLink_PortName2()
   * @model
   * @generated
   */
  String getPortName2();

  /**
   * Sets the value of the '{@link org.xtext.example.blocXML.Link#getPortName2 <em>Port Name2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port Name2</em>' attribute.
   * @see #getPortName2()
   * @generated
   */
  void setPortName2(String value);

  /**
   * Returns the value of the '<em><b>Balise Fermante</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Balise Fermante</em>' attribute.
   * @see #setBaliseFermante(String)
   * @see org.xtext.example.blocXML.BlocXMLPackage#getLink_BaliseFermante()
   * @model
   * @generated
   */
  String getBaliseFermante();

  /**
   * Sets the value of the '{@link org.xtext.example.blocXML.Link#getBaliseFermante <em>Balise Fermante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Balise Fermante</em>' attribute.
   * @see #getBaliseFermante()
   * @generated
   */
  void setBaliseFermante(String value);

} // Link
