/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.blocXML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.blocXML.Node#getNodeName <em>Node Name</em>}</li>
 *   <li>{@link org.xtext.example.blocXML.Node#getLinks <em>Links</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.blocXML.BlocXMLPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Name</em>' attribute.
   * @see #setNodeName(String)
   * @see org.xtext.example.blocXML.BlocXMLPackage#getNode_NodeName()
   * @model
   * @generated
   */
  String getNodeName();

  /**
   * Sets the value of the '{@link org.xtext.example.blocXML.Node#getNodeName <em>Node Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Name</em>' attribute.
   * @see #getNodeName()
   * @generated
   */
  void setNodeName(String value);

  /**
   * Returns the value of the '<em><b>Links</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.blocXML.Link}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links</em>' containment reference list.
   * @see org.xtext.example.blocXML.BlocXMLPackage#getNode_Links()
   * @model containment="true"
   * @generated
   */
  EList<Link> getLinks();

} // Node
