/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.blocXML.ui.internal.BlocXMLActivator;

public class BlocXMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BlocXMLActivator.getInstance().getInjector("org.xtext.example.BlocXML");
	}

}
