/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.blocXML.ui.internal.BlocXMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BlocXMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BlocXMLActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BlocXMLActivator activator = BlocXMLActivator.getInstance();
		return activator != null ? activator.getInjector(BlocXMLActivator.ORG_XTEXT_EXAMPLE_BLOCXML) : null;
	}

}
