/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalBlocXMLParser;
import org.xtext.example.services.BlocXMLGrammarAccess;

public class BlocXMLParser extends AbstractAntlrParser {

	@Inject
	private BlocXMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBlocXMLParser createParser(XtextTokenStream stream) {
		return new InternalBlocXMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ExportModel";
	}

	public BlocXMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BlocXMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
