/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.BlocXMLRuntimeModule;
import org.xtext.example.BlocXMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BlocXMLIdeSetup extends BlocXMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BlocXMLRuntimeModule(), new BlocXMLIdeModule()));
	}
	
}
