/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBlocXMLScopeProvider extends DelegatingScopeProvider {
}
